using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Chaosbound.Gameplay.Threat.ValueObjects;

namespace Chaosbound.Core.Runtime.Enemies
{
    /// <summary>
    /// Represents an immutable tactical composition generated by the EnemySolver.
    /// The composition is a declarative model describing which standard enemy
    /// variants should participate in the encounter.
    /// </summary>
    public sealed class EnemyComposition
    {
        private readonly IReadOnlyList<EnemyCompositionEntry> m_Entries;

        public EnemyComposition(
            IEnumerable<EnemyCompositionEntry> entries)
        {
            if (entries == null)
                throw new ArgumentNullException(nameof(entries));

            List<EnemyCompositionEntry> list = entries.ToList();

            m_Entries = new ReadOnlyCollection<EnemyCompositionEntry>(list);
        }

        /// <summary>
        /// Gets the immutable composition entries.
        /// </summary>
        public IReadOnlyList<EnemyCompositionEntry> Entries => m_Entries;

        /// <summary>
        /// Gets whether the composition contains no entries.
        /// </summary>
        public bool IsEmpty => m_Entries.Count == 0;

        /// <summary>
        /// Gets how many different enemy variants compose this composition.
        /// </summary>
        public int VariantCount => m_Entries.Count;

        /// <summary>
        /// Gets the total number of enemies represented by this composition.
        /// </summary>
        public int TotalEnemyCount =>
            m_Entries.Sum(entry => entry.Quantity);

        /// <summary>
        /// Gets the total threat cost represented by the composition.
        /// </summary>
        public ThreatCost TotalThreatCost =>
            new ThreatCost(
                m_Entries.Sum(entry => entry.TotalThreatCost.Value));

        /// <summary>
        /// Returns whether the specified variant exists in the composition.
        /// </summary>
        public bool Contains(
            EnemyVariantData variant)
        {
            return IndexOf(variant) >= 0;
        }

        /// <summary>
        /// Attempts to retrieve the entry corresponding to the specified variant.
        /// </summary>
        public bool TryGetEntry(
            EnemyVariantData variant,
            out EnemyCompositionEntry entry)
        {
            int index = IndexOf(variant);

            if (index >= 0)
            {
                entry = m_Entries[index];
                return true;
            }

            entry = null;
            return false;
        }

        /// <summary>
        /// Finds the index of the specified variant.
        /// Returns -1 if the variant is not present.
        /// </summary>
        private int IndexOf(
            EnemyVariantData variant)
        {
            if (variant == null)
                throw new ArgumentNullException(nameof(variant));

            for (int i = 0; i < m_Entries.Count; i++)
            {
                if (m_Entries[i].Variant == variant)
                    return i;
            }

            return -1;
        }
    }
}